server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Soporte para React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al Backend en la subred privada
    location /api/ {
        proxy_pass http://172.31.40.129:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    server_tokens off;   # Ocultar version de nginx
}
